casbin:
  storeType: file
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_db
    username: tomato
    password: tomato
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org.springframework.security: trace