server:
  port: 8081
spring:
  boot:
    admin:
      client:
        # 要注册的Spring Boot管理服务器的URL。
        url: http://localhost:8088
        password: "password"
        username: "user"
  application:
    name: spring-boot-admin-client
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true