server:
  port: 8081
spring:
  boot:
    admin:
      client:
        url: http://localhost:8088
  application:
    name: spring-boot-admin-client
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true