---
spring:
  profiles: test
  feign.debug.url:
    base: http://127.0.0.1:9000
    data-compilation: http://127.0.0.1:9011
  data-spider: http://127.0.0.1:9106
  hydro-forecast-short: http://127.0.0.1:9004
  hydrodynamic-waterquality-1d: http://127.0.0.1:9006
  monitor: http://127.0.0.1:9103
  quality-manage: http://127.0.0.1:9017
  reservoir-operation: http://127.0.0.1:9015
  river-lake-health: http://127.0.0.1:9016
  system: http://127.0.0.1:9002
  water-resource-allocation: http://127.0.0.1:9009
  spring:
  cloud:
  nacos:
  discovery:
  register-enabled: false
---