# 激活环境配置
spring:
  profiles:
    active: prod
  application:
    name: spring-boot-properties

application:
  name: dev环境
  version: dev环境

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080

---
# 测试环境配置
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8081

---

# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8082