server:
  # 端口设置
  port: 8080
  # 访问路径
  servlet:
    context-path: /learn
logging:
  # 应用程序终止时释放日志资源
  register-shutdown-hook: true
spring:
  output:
    ansi:
      # 控制台彩色输出
      enabled: always
  application:
    name: spring-boot-log